CREATE DATABASE SkinCancerDW;
USE SkinCancerDW;
CREATE TABLE FactLesions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SourceURL VARCHAR(700),
    Label VARCHAR(50),
    LocalPath VARCHAR(500),
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);